/* ============================================================================
   League of Bot — curated dataset
   ----------------------------------------------------------------------------
   Champion + item ART come free from Riot Data Dragon (auto-updates to latest
   patch). The CURATION below — what's spicy, what synergizes, what to build —
   is hand-made. That judgment is the moat.

   MAINTENANCE:
   - Champion ids must match ddragon (Kog'Maw -> "KogMaw", Wukong -> "MonkeyKing").
   - Item builds reference display NAMES; app.js resolves them to icons against
     the live item.json. If an item is renamed/removed, the on-load validator
     logs it to the browser console — bump reviewedPatch and fix the name.
   - Comp archetypes / duo synergies are near-evergreen (review a few times/yr).
     Item builds are volatile (review when the item system changes). See MAINTENANCE.md.
   ========================================================================== */

const CURATION_META = { reviewedPatch: '16.14' };

// --- Mode 1: Spicy Solo Picks (off-meta but viable) -------------------------
// build.skill = ability max order · build.path = purchase order (start → core)
const SPICY = [
  { id: 'KogMaw', role: 'Mid', why: 'AP Kog’Maw — bio-arcane barrage melts anyone who walks up. Poke them off the map.',
    build: { skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Nashor's Tooth","Riftmaker","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Tristana', role: 'Mid', why: 'AP Trist — the rocket-jump one-shot combo nobody expects at 14 minutes.',
    build: { rune: 'Electrocute · Sorcery', skill: 'E → W → Q', path: ["Doran's Ring","Sorcerer's Shoes","Lich Bane","Nashor's Tooth","Rabadon's Deathcap","Zhonya's Hourglass"] } },
  { id: 'Ziggs', role: 'Bot', why: 'Artillery ADC. Siege towers from a screen away and never get touched.',
    build: { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Swain', role: 'Support', why: 'Roots, a drain-tank ult, and lane bully from level 1. Nobody enjoys this matchup.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'E → W → Q', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Heimerdinger', role: 'Support', why: 'Turrets + stun grenade. Turn the bot lane into a no-go zone.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Teemo', role: 'Support', why: 'Blind their ADC, shroom the lane. Pure psychological warfare.',
    build: { rune: 'Arcane Comet · Domination', skill: 'E → Q → W', path: ["World Atlas","Sorcerer's Shoes","Nashor's Tooth","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap"] } },
  { id: 'Karthus', role: 'Jungle', why: 'Farm to infinity, then press R across the whole map for global steals.',
    build: { rune: 'Dark Harvest · Precision', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Mordekaiser', role: 'Mid', why: 'Drag their carry to the death realm for a guaranteed 1v1.',
    build: { rune: 'Conqueror · Resolve', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Sett', role: 'Support', why: 'Grab-and-slam their backline. A bruiser support that actually kills people.',
    build: { rune: 'Aftershock · Precision', skill: 'W → E → Q', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Sterak's Gage","Sunfire Aegis","Thornmail"] } },
  { id: 'Malphite', role: 'Bot', why: 'Rock-solid ADC. Q-poke, W-shred, and an ult that starts the wombo.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Rod of Ages","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Yasuo', role: 'Bot', why: 'Windwall the enemy ADC into irrelevance. Pair with a knock-up support.',
    build: { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Immortal Shieldbow","Infinity Edge","Bloodthirster","Death's Dance"] } },
  { id: 'Pyke', role: 'Mid', why: 'Roaming assassin in mid. Reset ult = free gold for the whole team.',
    build: { rune: 'Electrocute · Sorcery', skill: 'Q → E → W', path: ["Doran's Shield","Mercury's Treads","Youmuu's Ghostblade","Umbral Glaive","Serylda's Grudge","Edge of Night"] } },
  { id: 'Vladimir', role: 'Top', why: 'Pool the jungler’s gank and scale into an unkillable raid boss.',
    build: { rune: 'Stormraider’s Surge · Resolve', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Riftmaker","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Neeko', role: 'Support', why: 'Disguise as a minion, then AOE-root the entire enemy team.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Zhonya's Hourglass"] } },
  { id: 'Zilean', role: 'Support', why: 'Double-bomb stun and an ult that undoes death. Frustration incarnate.',
    build: { rune: 'Summon Aery · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Cosmic Drive","Rabadon's Deathcap","Zhonya's Hourglass"] } },
  { id: 'Veigar', role: 'Support', why: 'Cage them in, stack infinite AP, and eventually one-shot everyone.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Rod of Ages","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Singed', role: 'Top', why: 'Run it down, fling them into your team, and watch the enemy tilt.',
    build: { rune: 'Stormraider’s Surge · Resolve', skill: 'Q → E → W', path: ["Rod of Ages","Mercury's Treads","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Cryptbloom"] } },
  { id: 'Cassiopeia', role: 'Mid', why: 'No boots, all poison. Grovel-ground them and melt the lane.',
    build: { rune: 'Conqueror · Sorcery', skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Seraphine', role: 'Bot', why: 'Enchanter-carry hybrid. Shields, heals, and a screen-wide charm ult.',
    build: { rune: 'Summon Aery · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Ardent Censer","Void Staff"] } },
  { id: 'Kayle', role: 'Top', why: 'Suffer early, then become an untargetable ranged god at level 16.',
    build: { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Nashor's Tooth","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Shaco', role: 'Support', why: 'Fill every brush with boxes and turn face-checking into a jump-scare.',
    build: { rune: 'Arcane Comet · Domination', skill: 'W → E → Q', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Zhonya's Hourglass"] } },
  { id: 'Twitch', role: 'Support', why: 'Invisible level-2 all-ins. They will ping their jungler, and it won’t help.',
    build: { rune: 'Hail of Blades · Sorcery', skill: 'W → E → Q', path: ["World Atlas","Sorcerer's Shoes","Nashor's Tooth","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Garen', role: 'Mid', why: 'The assassin counter — silence, spin, and a true-damage execute on the villain.',
    build: { rune: 'Conqueror · Sorcery', skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] } },
  { id: 'Vayne', role: 'Top', why: 'Kite the melee statue for 20 minutes and condemn anyone who dares to jump you.',
    build: { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Blade of the Ruined King","Guinsoo's Rageblade","Wit's End","Lord Dominik's Regards"] } },
  { id: 'Shen', role: 'Support', why: 'Taunt-peel your carry in lane, then press R and win a fight two screens away.',
    build: { rune: 'Guardian · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Knight's Vow","Kaenic Rookern","Thornmail"] } },
  { id: 'Morgana', role: 'Jungle', why: 'W melts camps, and every gank arrives with a three-second root attached.',
    build: { rune: 'Dark Harvest · Sorcery', skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Tryndamere', role: 'Mid', why: 'Right-click the wave, right-click the tower, press R, refuse to die.',
    build: { rune: 'Lethal Tempo · Sorcery', skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Yun Tal Wildarrows","Infinity Edge","Bloodthirster","Death's Dance"] } },
  { id: 'Camille', role: 'Support', why: 'Hookshot-stun engage and an ult that jails their carry in a 1v1 arena.',
    build: { rune: 'Aftershock · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Plated Steelcaps","Iceborn Gauntlet","Sterak's Gage","Knight's Vow","Death's Dance"] } },
  { id: 'Ashe', role: 'Support', why: 'Perma-slow poke, vision hawks, and a global engage arrow. Who needs an ADC?',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'W → Q → E', path: ["World Atlas","Berserker's Greaves","Imperial Mandate","Runaan's Hurricane","Rapid Firecannon","Serylda's Grudge"] } },
  { id: 'Zyra', role: 'Jungle', why: 'The jungle is a garden now. Plants clear camps for you while you plot ganks.',
    build: { rune: 'Dark Harvest · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Soraka', role: 'Top', why: 'Q-sustain bullying in lane, then heal-bot the map from a side lane. Pro-play approved.',
    build: { rune: 'Grasp of the Undying · Inspiration', skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Cosmic Drive","Rabadon's Deathcap"] } },
  { id: 'Brand', role: 'Jungle', why: 'Everything burns. Full-clear with W and arrive to every gank with %HP fire attached.',
    build: { rune: 'Dark Harvest · Sorcery', skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Syndra', role: 'Bot', why: 'A mage lane bully in bot — stack spheres into a point-and-click execute on their ADC.',
    build: { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Luden's Echo","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Poppy', role: 'Support', why: 'Press W and every dash in their comp simply stops working. Bonk.',
    build: { rune: 'Aftershock · Inspiration', skill: 'Q → W → E', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Knight's Vow","Thornmail","Kaenic Rookern"] } },
  { id: 'Pantheon', role: 'Mid', why: 'Point-and-click stun, spear poke, and a level-6 ult that ganks bot from mid.',
    build: { rune: 'Conqueror · Sorcery', skill: 'Q → W → E', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Eclipse","Serylda's Grudge","Edge of Night"] } },
  { id: 'Teemo', role: 'Top', why: 'Blind their bruiser, shroom the whole side lane, and turn splitpushing into a minefield.',
    build: { rune: 'Press the Attack · Sorcery', skill: 'E → Q → W', path: ["Doran's Ring","Berserker's Greaves","Nashor's Tooth","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap"] } },
  { id: 'Kennen', role: 'Top', why: 'A ranged AP top that out-pokes melee and flips a teamfight with a stun-storm ult.',
    build: { rune: 'Electrocute · Sorcery', skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Heimerdinger', role: 'Top', why: 'Turret up and make the lane a no-go zone. Nobody enjoys diving a wall of rockets.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Ziggs', role: 'Top', why: 'Artillery top — shove the wave, chunk them off CS, and demolish the tower from a screen away.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Cassiopeia', role: 'Top', why: 'No boots, all poison. Grovel-ground the melee statue and drown the side lane in miasma.',
    build: { rune: 'Conqueror · Sorcery', skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Neeko', role: 'Top', why: 'Disguise as a minion, then AoE-root the dive and burst the whole enemy team in one combo.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Sylas', role: 'Top', why: 'Steal their best ult and use it against them. A drain-fighter that snowballs off every skirmish.',
    build: { rune: 'Conqueror · Resolve', skill: 'E → Q → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Yasuo', role: 'Top', why: 'Windwall their poke, ride the wave with Q, and dash through minions to duel anyone up top.',
    build: { rune: 'Lethal Tempo · Resolve', skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] } },
  { id: 'Gragas', role: 'Top', why: 'Body-slam engage and a cask that flings them into your team. A drunk bruiser with a wombo button.',
    build: { rune: 'Grasp of the Undying · Resolve', skill: 'E → Q → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Quinn', role: 'Top', why: 'A ranged AD top that out-trades melee, roams with her ult, and splitpushes the map to death.',
    build: { rune: 'Press the Attack · Domination', skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Profane Hydra","Serylda's Grudge","Edge of Night"] } },
  { id: 'Shaco', role: 'Jungle', why: 'Box the whole jungle and jump-scare their carry. Cheese ganks that end careers.',
    build: { rune: 'Hail of Blades · Sorcery', skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Profane Hydra","Serylda's Grudge","Edge of Night"] } },
  { id: 'Fiddlesticks', role: 'Jungle', why: 'Silence-fear a whole camp, then teleport-ult into the backline for a screen-wide horror show.',
    build: { rune: 'Electrocute · Inspiration', skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Nunu', role: 'Jungle', why: 'Roll a snowball across the map and freeze their carry solid. The most fun gank in the game.',
    build: { rune: 'Aftershock · Inspiration', skill: 'W → E → Q', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Rammus', role: 'Jungle', why: 'Taunt their fed carry, roll into the fight, and reflect their own autos back at them. OK.',
    build: { rune: 'Grasp of the Undying · Inspiration', skill: 'W → Q → E', path: ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Thornmail","Kaenic Rookern","Jak'Sho, The Protean"] } },
  { id: 'Malphite', role: 'Jungle', why: 'AP Malphite jungle — clear with W, then flash-ult the grouped team for a one-shot wombo.',
    build: { rune: 'Grasp of the Undying · Sorcery', skill: 'W → E → Q', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } },
  { id: 'Lillia', role: 'Jungle', why: 'Dreamdust burns down camps fast, then a screen-wide sleep ult sets up a full-team follow-up.',
    build: { rune: 'Conqueror · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Nashor's Tooth","Riftmaker","Rabadon's Deathcap","Zhonya's Hourglass"] } },
  { id: 'Ivern', role: 'Jungle', why: 'Never kill a camp — free them for gold and buff your carry with a shield and a knock-up sapling.',
    build: { rune: 'Guardian · Inspiration', skill: 'Q → W → E', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Mordekaiser', role: 'Jungle', why: 'AP jungle Morde — clear with a Q-E combo and drag their carry to the death realm for a free 1v1.',
    build: { rune: 'Conqueror · Resolve', skill: 'Q → E → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Taliyah', role: 'Jungle', why: 'Weave through the jungle, seismic-shove their carry into a wall, and control the whole map with rocks.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Sylas', role: 'Jungle', why: 'Clear fast with a drain Q and gank with a hijacked ult. A skirmishing menace out of the jungle.',
    build: { rune: 'Conqueror · Domination', skill: 'E → Q → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Teemo', role: 'Jungle', why: 'Shroom every entrance and every gank path. The enemy jungle becomes a poison maze.',
    build: { rune: 'Press the Attack · Sorcery', skill: 'E → Q → W', path: ["Doran's Ring","Berserker's Greaves","Nashor's Tooth","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap"] } },
  { id: 'Swain', role: 'Mid', why: 'A drain-tank mid — root them, ult in a teamfight, and heal to full off the whole enemy team.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'E → W → Q', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Heimerdinger', role: 'Mid', why: 'Turret-wall the mid lane, poke with rockets, and make roaming into your lane suicidal.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Ziggs', role: 'Mid', why: 'Zone the whole lane with bombs, shove it in, and roam-siege every tower on the map.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Seraphine', role: 'Mid', why: 'A shield-and-charm mid — poke, heal your dive, and hit the whole team with a screen-wide root ult.',
    build: { rune: 'Summon Aery · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Neeko', role: 'Mid', why: 'Clone their mid, walk into the fog, and land a pop-up AoE root into a full-team burst.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Malphite', role: 'Mid', why: 'AP Malphite mid — Q-poke and shred, then unstoppable-ult flank the squishies for the one-shot.',
    build: { rune: 'Arcane Comet · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] } },
  { id: 'Karthus', role: 'Mid', why: 'Push and roam with a global ult from mid — steal kills across the map and snowball every lane.',
    build: { rune: 'Dark Harvest · Precision', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Swain', role: 'Bot', why: 'A drain-mage bot — root the ADC, out-sustain every trade, and ult the 2v2 for a free double.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'E → W → Q', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Karthus', role: 'Bot', why: 'Farm bot with a screen-wide death aura, then press R for map-wide kill steals. The APC menace.',
    build: { rune: 'Dark Harvest · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Heimerdinger', role: 'Bot', why: 'Two turrets in the bot lane makes it a fortress. Poke them out and never let them walk up.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Veigar', role: 'Bot', why: 'Cage the ADC, stack infinite AP, and eventually point-and-click one-shot everyone bot side.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Cassiopeia', role: 'Bot', why: 'Grovel-ground the enemy ADC and drown the bot lane in poison. No dashes, no escape.',
    build: { rune: 'Conqueror · Sorcery', skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Brand', role: 'Bot', why: 'Everything burns. Passive-detonate their whole lane and out-poke any ADC into oblivion.',
    build: { rune: 'Arcane Comet · Domination', skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] } },
  { id: 'Vladimir', role: 'Bot', why: 'Pool the all-in, scale off healing, and become an unkillable AP carry from the bot lane.',
    build: { rune: 'Stormraider’s Surge · Resolve', skill: 'Q → E → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Neeko', role: 'Bot', why: 'A pop-up-root APC — hide as a minion, land the AoE stun, and burst their whole bot side.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Mordekaiser', role: 'Bot', why: 'Drag the enemy ADC to the death realm and win a guaranteed 1v1 every cooldown.',
    build: { rune: 'Conqueror · Resolve', skill: 'Q → E → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
  { id: 'Karma', role: 'Bot', why: 'A poke-carry bot — mantra-root, shield the aggression, and chunk them out with empowered Q.',
    build: { rune: 'Arcane Comet · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Shadowflame","Void Staff"] } },
  { id: 'Velkoz', role: 'Support', why: 'A pure-poke artillery support — chunk them off the map and true-damage burst the whole lane.',
    build: { rune: 'Arcane Comet · Domination', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Xerath', role: 'Support', why: 'Siege the bot lane from screen-length away. Stun, poke, and never let them near the wave.',
    build: { rune: 'Arcane Comet · Inspiration', skill: 'Q → W → E', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } },
  { id: 'Mordekaiser', role: 'Support', why: 'A bruiser support that actually kills — E them into your ADC, then ult their carry to the shadow realm.',
    build: { rune: 'Grasp of the Undying · Precision', skill: 'Q → E → W', path: ["Rod of Ages","Sorcerer's Shoes","Riftmaker","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } },
];


// --- Mode 1b: Classic Solo Picks (conventional meta) ----------------------
// Lean entries — build + runes come from the shared BUILDS / RUNES libraries
// (same pattern as classic DUOS). Off-meta picks live in SPICY with inline builds.
const CLASSIC = [
  { id: 'Aatrox', role: 'Top', why: 'The blade of the darkin — sweeping Q combos, a healing ult, and a duelist who wins every side lane.' },
  { id: 'Darius', role: 'Top', why: 'Land the outer-axe pull and the lane is over. Stack Hemorrhage and press R for the reset snowball.' },
  { id: 'Garen', role: 'Top', why: 'Silence, spin, and a true-damage execute on the fed enemy. Simple, sturdy, and always relevant.' },
  { id: 'Fiora', role: 'Top', why: 'Vitals, parries, and a duel nobody wins. The best 1v1 splitpusher in the game.' },
  { id: 'Camille', role: 'Top', why: 'Hookshot engage, a shielded all-in, and an ult that jails their carry for a clean 1v1.' },
  { id: 'Jax', role: 'Top', why: 'Empowered leaps and a Counter Strike stun. Scales into an unkillable late-game bruiser.' },
  { id: 'Irelia', role: 'Top', why: 'Reset on minions, stun the wave, and snowball a lead into an unstoppable dive threat.' },
  { id: 'Renekton', role: 'Top', why: 'The lane bully — dominate early with fury combos and dive them before they ever scale.' },
  { id: 'Sett', role: 'Top', why: 'Punch, punch, grab-and-slam. A brawler who face-tanks the fight and throws their carry into yours.' },
  { id: 'Ornn', role: 'Top', why: 'A tank that out-scales carries — upgrade the whole team’s items and knock them into a wall.' },
  { id: 'Malphite', role: 'Top', why: 'Rock-solid frontline. Q-shred the lane, then flash-ult to start a wombo teamfight.' },
  { id: 'Shen', role: 'Top', why: 'Taunt-peel and a global ult that wins a fight two lanes away. Map pressure incarnate.' },
  { id: 'KSante', role: 'Top', why: 'A juggernaut who becomes an assassin in his ult — drag their carry out and delete it.' },
  { id: 'Gwen', role: 'Top', why: 'Snip-snip through the frontline. Untargetable in the mist and unkillable once she scales.' },
  { id: 'Riven', role: 'Top', why: 'Animation-cancel combos into a shielded, mobile burst-fighter that snowballs out of control.' },
  { id: 'LeeSin', role: 'Jungle', why: 'Early-game tempo king — Q-Q insec kicks, ward-hops, and ganks that never stop coming.' },
  { id: 'Viego', role: 'Jungle', why: 'Kill anything and steal its kit. A snowballing skirmisher who resets through whole teamfights.' },
  { id: 'Khazix', role: 'Jungle', why: 'Isolate, leap, delete. Evolve for the pick and vanish before anyone can retaliate.' },
  { id: 'Graves', role: 'Jungle', why: 'Double-barrel burst and the best jungle clear in the game. A marksman that duels bruisers.' },
  { id: 'Hecarim', role: 'Jungle', why: 'Ramp up move speed and run them down. Rear-line dives that end in a knockback wombo.' },
  { id: 'Vi', role: 'Jungle', why: 'Point-and-click ult onto their carry. The whole team follows the vault engage.' },
  { id: 'Kayn', role: 'Jungle', why: 'Choose your form — red for a healing bruiser, blue for a wall-phasing assassin. Scales fast either way.' },
  { id: 'JarvanIV', role: 'Jungle', why: 'Flag-drag knock-up into an ult that cages their carry for the team to collapse on.' },
  { id: 'Nocturne', role: 'Jungle', why: 'Global ult that removes vision and dives a lane from across the map. Fear-locks their carry.' },
  { id: 'Sejuani', role: 'Jungle', why: 'Permafrost engage — a tanky ult stun that starts the fight and never dies through it.' },
  { id: 'Amumu', role: 'Jungle', why: 'Bandage toss into a screen-wide ult stun. The single best wombo-comp initiator.' },
  { id: 'Zac', role: 'Jungle', why: 'Long-range blob engage and four-man knock-ups. A rubbery frontline that never stays dead.' },
  { id: 'Nidalee', role: 'Jungle', why: 'Spears from a screen away and lightning-fast clears. Bully their jungle and snowball early.' },
  { id: 'Diana', role: 'Jungle', why: 'Moonfall pull into a full AP burst combo. An assassin that ults a whole grouped team at once.' },
  { id: 'Elise', role: 'Jungle', why: 'Rappel-and-cocoon picks with a burst spider form. One of the strongest early gankers alive.' },
  { id: 'Ahri', role: 'Mid', why: 'Charm-into-combo picks and an ult that darts through walls to finish or escape. Slippery and safe.' },
  { id: 'Syndra', role: 'Mid', why: 'Stack spheres, land the stun, and point-and-click execute their carry off the map.' },
  { id: 'Orianna', role: 'Mid', why: 'The ball controls the fight — shield your dive and Shockwave their grouped team into your combo.' },
  { id: 'Viktor', role: 'Mid', why: 'Scale into a wave-clearing lategame monster with a chase-down laser and a chaos-storm ult.' },
  { id: 'Zed', role: 'Mid', why: 'Shadow combos and a Death Mark that erases any carry. The classic mid-lane assassin.' },
  { id: 'Talon', role: 'Mid', why: 'Rake, dash, and roam — vault over walls to gank side lanes and snowball the map.' },
  { id: 'Katarina', role: 'Mid', why: 'A daggers-everywhere reset machine. One kill mid-fight becomes a pentakill.' },
  { id: 'Fizz', role: 'Mid', why: 'Trickster dashes, an untargetable pole-vault, and a shark ult that guarantees the kill.' },
  { id: 'Kassadin', role: 'Mid', why: 'Suffer early, then Riftwalk around the map one-shotting mages once he hits level 16.' },
  { id: 'Leblanc', role: 'Mid', why: 'Distortion in, chain-and-burst, distortion out. The most frustrating mid-lane picker.' },
  { id: 'Lux', role: 'Mid', why: 'Bind them, then vaporize with a screen-wide laser. Punishing poke and huge burst.' },
  { id: 'Anivia', role: 'Mid', why: 'Wall them off, stun through the egg, and zone the whole map with a permanent ult.' },
  { id: 'TwistedFate', role: 'Mid', why: 'Gold-card stun picks and a global ult that ganks any lane on the map. Pure tempo.' },
  { id: 'Yone', role: 'Mid', why: 'Two-stance duelist with a dash-back Q and a knock-up ult that sets up the whole fight.' },
  { id: 'Akali', role: 'Mid', why: 'Shroud-and-dash assassin who ignores towers and deletes carries through her smoke.' },
  { id: 'Jinx', role: 'Bot', why: 'Rocket the wave, reset on a kill, and rain hypercarry damage across the whole teamfight.' },
  { id: 'Caitlyn', role: 'Bot', why: 'The longest range in the game — traps, headshots, and an oppressive level-2 all-in.' },
  { id: 'Kaisa', role: 'Bot', why: 'Plasma-shred and an invisible ult dive. Builds AP or AD and out-scales every ADC late.' },
  { id: 'Jhin', role: 'Bot', why: 'Four-shot artistry — the fourth bullet crits, the ult snipes across the map. Pure style and damage.' },
  { id: 'Ezreal', role: 'Bot', why: 'Poke safely with mystic shots, then E away from every gank. The safest scaling carry.' },
  { id: 'Aphelios', role: 'Bot', why: 'Five guns, endless combos. A weapon-swapping hypercarry who out-damages the whole map late.' },
  { id: 'Ashe', role: 'Bot', why: 'Perma-slow poke and a global stun arrow that starts fights from across the map.' },
  { id: 'MissFortune', role: 'Bot', why: 'Double-up burst in lane and a Bullet Time ult that shreds a grouped enemy team.' },
  { id: 'Lucian', role: 'Bot', why: 'Double-tap dashes and relentless early pressure. Punishes the lane before scaling matters.' },
  { id: 'Xayah', role: 'Bot', why: 'Feather-recall combos, a self-peel untargetable ult, and huge AoE clean-up in fights.' },
  { id: 'Samira', role: 'Bot', why: 'Style-meter combos into a machine-gun ult that carves through a stunned enemy team.' },
  { id: 'Draven', role: 'Bot', why: 'Catch the spinning axes for the highest early damage in the game and snowball adoration gold.' },
  { id: 'Varus', role: 'Bot', why: 'Poke them down with charged Q, then chain-root the team with a piercing ult.' },
  { id: 'Zeri', role: 'Bot', why: 'Machine-gun autos and wall-hopping mobility. An unkillable late-game kiting carry.' },
  { id: 'Sivir', role: 'Bot', why: 'Spellshield the key ability, wave-clear for free, and speed-boost the team into a fight.' },
  { id: 'Thresh', role: 'Support', why: 'Hook, flay, lantern. The highest-skill playmaker support — every landed hook is a kill.' },
  { id: 'Leona', role: 'Support', why: 'Point-and-click stun chains that lock a target down from level 1. The best all-in engage.' },
  { id: 'Nautilus', role: 'Support', why: 'Hook, root, and a knock-up ult. Chain CC that guarantees your carry gets the kill.' },
  { id: 'Lulu', role: 'Support', why: 'Shield, polymorph, and a knock-up ult that keeps your hypercarry alive to 1v9.' },
  { id: 'Nami', role: 'Support', why: 'Bubble stuns, empowered autos, and a wave that swings the whole teamfight.' },
  { id: 'Karma', role: 'Support', why: 'Mantra shields and roots — poke them down and empower your carry from level 1.' },
  { id: 'Rakan', role: 'Support', why: 'A charming, dashing playmaker who engages and peels in the same fight. Pairs with everything.' },
  { id: 'Milio', role: 'Support', why: 'Cleanse CC, extend your carry’s range, and chain-heal the backline through any fight.' },
  { id: 'Soraka', role: 'Support', why: 'Global heals and a silence. Keep the whole team topped off and simply out-sustain the enemy.' },
  { id: 'Rell', role: 'Support', why: 'Weld to an ally, then unleash a full-lane stun engage that starts the wombo.' },
  { id: 'Morgana', role: 'Support', why: 'Black Shield the key CC and root them for days. The counter to every engage support.' },
  { id: 'Blitzcrank', role: 'Support', why: 'One hook decides the lane. Grab, knock-up, silence — a single pick ends fights.' },
  { id: 'Alistar', role: 'Support', why: 'Headbutt-pulverize combos and an unkillable ult. Boop their carry straight into yours.' },
  { id: 'Braum', role: 'Support', why: 'Stack the passive stun, wall projectiles, and shield your carry through everything.' },
  { id: 'Janna', role: 'Support', why: 'Disengage everything — shields, slows, and a monsoon ult that undoes their entire engage.' },
];

// --- Mode 2: Bot Lane Duos (the killer differentiator) ----------------------
const DUOS = [
  { adc: 'Draven',      sup: 'Thresh',    tag: 'All-In',     why: 'Thresh hook + lantern snowballs Draven’s adoration into a lead nobody comes back from.' },
  { adc: 'Ezreal',      sup: 'Karma',     tag: 'Poke',       why: 'Endless mystic shots and mantra-Q. Chip them to zero before a fight even starts.' },
  { adc: 'KogMaw',      sup: 'Lulu',      tag: 'Hypercarry', why: 'Lulu babysits early, then buffs Kog into a late-game shredding machine.' },
  { adc: 'Samira',      sup: 'Rell',      tag: 'Wombo',      why: 'Rell stuns the whole lane, Samira ults through it for the highlight-reel penta.' },
  { adc: 'Caitlyn',     sup: 'Morgana',   tag: 'Lane Bully', why: 'Binding into traps into headshots. The most oppressive level-2 lane in the game.' },
  { adc: 'Xayah',       sup: 'Rakan',     tag: 'Combo',      why: 'The canonical lovers’ lane — built-in engage, peel, and a shared recall.' },
  { adc: 'Vayne',       sup: 'Lulu',      tag: 'Protect',    why: 'Shield, polymorph, and peel for the late-game monster who 1v9s.' },
  { adc: 'Twitch',      sup: 'Yuumi',     tag: 'Cheese',     why: 'Perma-stick an invisible rat. Roll a stealth ambush and giggle to Challenger.' },
  { adc: 'MissFortune', sup: 'Leona',     tag: 'Wombo',      why: 'Leona chains CC, MF ults the frozen lane. Delete two health bars instantly.' },
  { adc: 'Ashe',        sup: 'Zyra',      tag: 'Zone',       why: 'Plants + a global arrow. Control every choke and never let them walk up.' },
  { adc: 'Lucian',      sup: 'Nami',      tag: 'Tempo',      why: 'The classic aggressive duo — empowered autos and relentless early pressure.' },
  { adc: 'Jinx',        sup: 'Nautilus',  tag: 'Engage',     why: 'Chain CC lets Jinx reset and rocket the map. Snowball into a fiesta.' },
  { adc: 'Nilah',       sup: 'Yuumi',     tag: 'Scaling',    why: 'Nilah shares Yuumi’s heals with the whole team. An unkillable teamfight duo.' },
  { adc: 'Kalista',     sup: 'Thresh',    tag: 'All-In',     why: 'Fate’s Call flings Thresh into a flay-hook combo. Dive them under tower.' },
  { adc: 'Sivir',       sup: 'Karma',     tag: 'Speed Poke', why: 'Global movement speed + poke. Shove waves fast and roam the map together.' },
  { adc: 'Kaisa',       sup: 'Nautilus',  tag: 'Dive',       why: 'Naut locks them down, Kai’Sa pops the plasma stacks and ults in to finish the job.' },
  { adc: 'Senna',       sup: 'TahmKench', tag: 'Fasting',    why: 'The fasting lane — Tahm hoovers the gold while Senna stacks souls into infinite range.' },
  { adc: 'Varus',       sup: 'Braum',     tag: 'Chain CC',   why: 'Varus ult roots the first target, Braum stuns the next. Someone is always chained down.' },
  { adc: 'Zeri',        sup: 'Milio',     tag: 'Zoomies',    why: 'Milio stacks range and move speed on a champion who was already uncatchable. Kite forever.' },
  { adc: 'Draven',      sup: 'Blitzcrank',tag: 'Kill Lane',  why: 'A landed hook next to Draven is a kill, a cashed adoration stack, and a tilted enemy.' },
  { adc: 'Ezreal',      sup: 'Yuumi',     tag: 'Poke Taxi',  why: 'Yuumi rides a champion nobody can touch. Infinite sustain on infinite poke.' },
  { adc: 'Caitlyn',     sup: 'Lux',       tag: 'Snare Stack',why: 'Root into trap into headshot into another root. The lane becomes a 650-range minefield.' },
  { adc: 'Jinx',        sup: 'Thresh',    tag: 'Peel',       why: 'Thresh makes diving Jinx a death sentence, and the lantern makes her resets consequence-free.' },
  { adc: 'Kalista',     sup: 'Rell',      tag: 'Wombo',      why: 'Fate’s Call launches Rell into the enemy like a magnetic missile. Crash, stun, clean up.' },
  { adc: 'Aphelios',    sup: 'Sona',      tag: 'Scaling',    why: 'Two of the hardest-scaling champions in the game. Survive lane and own every fight after 30.' },
  { adc: 'Yasuo',       sup: 'Alistar',   tag: 'Knock-Up',   why: 'Headbutt-pulverize is a free Yasuo ult every single rotation. The bot lane blender.' },
  { adc: 'MissFortune', sup: 'Sona',      tag: 'Double Ult', why: 'Crescendo holds them still for the full channel of Bullet Time. Two buttons, one ace.' },
];

/* --- Mode 2b: Spicy Duos (off-meta bot lanes) --------------------------------
   Same shape as DUOS plus an optional `builds` override: these lanes play
   champions OUT of their conventional role, so the shared BUILDS entry would be
   wrong. builds.adc / builds.sup (when present) win over BUILDS[id]. */
const SPICY_DUOS = [
  { adc: 'Yasuo', sup: 'Malphite', tag: 'Knock-Up', why: 'Malphite ult is the world’s largest Yasuo ult button. Unstoppable force, meet windwall.',
    builds: { sup: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Rod of Ages","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } } },
  { adc: 'Ziggs', sup: 'Heimerdinger', tag: 'Siege', why: 'Two demolition experts, one lane. The tower is gone by 14 minutes and so is their will to play.',
    builds: { sup: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } } },
  { adc: 'Vayne', sup: 'Taric', tag: 'Cheese', why: 'The infamous funnel lane — stun chains and invulnerability for the rat that never dies.',
    builds: { sup: { rune: 'Aftershock · Inspiration', skill: 'Q → W → E', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Thornmail"] } } },
  { adc: 'Karthus', sup: 'Sona', tag: 'Press R', why: 'Farm with a screen-wide death aura, then both of you press R and someone across the map dies.',
    builds: { adc: { rune: 'Dark Harvest · Sorcery', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } } },
  { adc: 'Brand', sup: 'Zyra', tag: 'Double Mage', why: 'No ADC, only fire and plants. Their support facechecks one brush and the lane is over.',
    builds: { adc: { rune: 'Dark Harvest · Sorcery', skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] } } },
  { adc: 'Samira', sup: 'Sett', tag: 'Brawl', why: 'Sett flings them into the blender and face-tanks the counter-engage. Style points mandatory.',
    builds: { sup: { rune: 'Aftershock · Precision', skill: 'W → E → Q', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Sterak's Gage","Sunfire Aegis","Thornmail"] } } },
  { adc: 'Seraphine', sup: 'Swain', tag: 'Drain', why: 'Two drain-scaling AP engines in one lane. Every extended trade heals you and kills them.',
    builds: { adc: { rune: 'Summon Aery · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Ardent Censer","Void Staff"] },
              sup: { rune: 'Arcane Comet · Inspiration', skill: 'E → W → Q', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] } } },
  { adc: 'Veigar', sup: 'Lulu', tag: 'Scaling Cage', why: 'Lulu keeps the tiny devil alive while the AP stacks tick toward one-shot territory.',
    builds: { adc: { rune: 'Arcane Comet · Inspiration', skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Rod of Ages","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] } } },
];

// --- Mode 3: Full Team Comps (themed, with a full breakdown) -----------------
const COMPS = [
  {
    name: 'Poke & Siege', emoji: '🎯',
    champs: [ {id:'Jayce',role:'Top'}, {id:'Nidalee',role:'Jungle'}, {id:'Xerath',role:'Mid'}, {id:'Ziggs',role:'Bot'}, {id:'Karma',role:'Support'} ],
    overview: 'Long-range damage that whittles the enemy down before a fight even starts, then takes towers while they’re too low to contest.',
    spike: 'Mid game',
    winCon: 'Chip them down from max range, take towers for free, and never let them force an engage.',
    play: [ 'Shove waves and poke them off the objective', 'Take towers and dragons with the health lead', 'Never facecheck — one landed engage and you lose the fight' ],
    weakness: 'Hard engage and flanks. One Malphite ult on the squishy backline erases the comp.'
  },
  {
    name: 'Wombo Dive', emoji: '💥',
    champs: [ {id:'Malphite',role:'Top'}, {id:'Amumu',role:'Jungle'}, {id:'Orianna',role:'Mid'}, {id:'Aphelios',role:'Bot'}, {id:'Rell',role:'Support'} ],
    overview: 'Stacked AOE ultimates that chain into one unstoppable teamfight combo. Land it once and the game is over.',
    spike: 'Mid–late (once ultimates are up)',
    winCon: 'One good engage ends the game. Land the chain of ults and ace them in four seconds.',
    play: [ 'Group and force fights around objectives', 'Find a flank or flash-engage to open', 'Call ults in order: engage → follow-up → clean-up' ],
    weakness: 'Disengage, poke, and split-push. If they scatter before the combo lands, you have nothing.'
  },
  {
    name: 'Protect the Carry', emoji: '🛡️',
    champs: [ {id:'Shen',role:'Top'}, {id:'Ivern',role:'Jungle'}, {id:'Orianna',role:'Mid'}, {id:'KogMaw',role:'Bot'}, {id:'Lulu',role:'Support'} ],
    overview: 'One hyper-scaling carry and four champions whose entire job is to keep them alive long enough to 1v9.',
    spike: 'Late game',
    winCon: 'Everything exists to keep Kog’Maw alive. Peel, shield, and let him melt them front-to-back.',
    play: [ 'Survive early and farm the carry to full items', 'In fights, body-block and peel — never trade the carry', 'Let the enemy commit, then melt them down' ],
    weakness: 'Assassins and hard dive that leap past the peel, and getting run over before the carry comes online.'
  },
  {
    name: 'Pick Comp', emoji: '🎣',
    champs: [ {id:'Camille',role:'Top'}, {id:'Nocturne',role:'Jungle'}, {id:'Ahri',role:'Mid'}, {id:'Jhin',role:'Bot'}, {id:'Thresh',role:'Support'} ],
    overview: 'Mobility and crowd control built to catch one target and delete them before a real 5v5 ever happens.',
    spike: 'Mid game',
    winCon: 'Catch one target out of position, turn every fight into a 5v4, and snowball the map.',
    play: [ 'Control vision and lurk around choke points', 'Force a pick, then collapse for the 5v4', 'Convert the numbers advantage into objectives' ],
    weakness: 'Grouped, disciplined teams that never split or facecheck. No picks means no plan.'
  },
  {
    name: 'Split Push 1-3-1', emoji: '🗺️',
    champs: [ {id:'Fiora',role:'Top'}, {id:'Nidalee',role:'Jungle'}, {id:'TwistedFate',role:'Mid'}, {id:'Sivir',role:'Bot'}, {id:'TahmKench',role:'Support'} ],
    overview: 'Duelists on the side lanes that pressure the map while global ults hold the middle and answer any fight.',
    spike: 'Mid–late',
    winCon: 'Pressure both side lanes. When they collapse on Fiora, TF/Sivir ult the 4v4 mid and take the map.',
    play: [ 'Send strong duelists to opposite side lanes', 'Trade objectives — take theirs while they answer your splitter', 'Use TF/global ults to swing any skirmish' ],
    weakness: 'Hard engage onto your mid group, and teams that 5-man dive the splitter with numbers.'
  },
  {
    name: 'Front-to-Back', emoji: '🧱',
    champs: [ {id:'Ornn',role:'Top'}, {id:'Sejuani',role:'Jungle'}, {id:'Orianna',role:'Mid'}, {id:'Aphelios',role:'Bot'}, {id:'Braum',role:'Support'} ],
    overview: 'An immovable tank wall in front and a hyper-carry safely dealing damage behind it. You simply out-last them.',
    spike: 'Late game',
    winCon: 'Stack tanks, walk at them, and let Aphelios delete their team from behind an unbreakable wall.',
    play: [ 'Stack tanks and walk at objectives together', 'Absorb their engage on the frontline', 'Let the carry auto them down from safety — never chase' ],
    weakness: 'Poke comps that chip you before you arrive, and flanks that skip the frontline entirely.'
  },
  {
    name: 'Global Pressure', emoji: '🌍',
    champs: [ {id:'Shen',role:'Top'}, {id:'Nocturne',role:'Jungle'}, {id:'TwistedFate',role:'Mid'}, {id:'Twitch',role:'Bot'}, {id:'Karma',role:'Support'} ],
    overview: 'Map-wide ultimates that let you win fights anywhere on the map before the enemy can rotate.',
    spike: 'Mid game',
    winCon: 'Use TF, Shen and Nocturne ults to turn every skirmish into a 5v4 and snowball the tempo lead.',
    play: [ 'Skirmish and invade to create numbers advantages', 'Use global ults to collapse on a fight the enemy thinks is even', 'Convert every won fight into an objective' ],
    weakness: 'Disciplined teams that only fight 5v5, and getting caught out while spread across the map.'
  },
  {
    name: 'Hyper-Scale Insurance', emoji: '⏳',
    champs: [ {id:'Kayle',role:'Top'}, {id:'Ivern',role:'Jungle'}, {id:'Orianna',role:'Mid'}, {id:'Vayne',role:'Bot'}, {id:'Lulu',role:'Support'} ],
    overview: 'Every member scales into a monster. You concede the early game to become unbeatable late.',
    spike: 'Late game',
    winCon: 'Survive to three items, then out-scale them — a maxed Kayle and Vayne simply win any late fight.',
    play: [ 'Farm safely and trade objectives for time', 'Avoid coin-flip early fights — you lose those', 'Once online, group and force fights you now win by default' ],
    weakness: 'Early-game snowball comps that end before you scale, and getting split-pushed off the map.'
  },
  {
    name: 'Dive the Backline', emoji: '🗡️',
    champs: [ {id:'Camille',role:'Top'}, {id:'Nocturne',role:'Jungle'}, {id:'Ahri',role:'Mid'}, {id:'Samira',role:'Bot'}, {id:'Rell',role:'Support'} ],
    overview: 'Multiple mobile threats that leap over the frontline and delete the enemy carries.',
    spike: 'Mid game',
    winCon: 'Collapse on their carry from three angles — once it dies, clean up the 5v4.',
    play: [ 'Find a flank or pick angle onto their backline', 'Commit hard together — half-dives feed', 'Kill the carry first, then mop up' ],
    weakness: 'Peel-heavy protect comps, disengage, and disciplined positioning that denies the dive.'
  },
  {
    name: 'Early Snowball', emoji: '⚡',
    champs: [ {id:'Jayce',role:'Top'}, {id:'Nidalee',role:'Jungle'}, {id:'Ahri',role:'Mid'}, {id:'Caitlyn',role:'Bot'}, {id:'Morgana',role:'Support'} ],
    overview: 'Oppressive early laners that snowball leads across the map and end before the enemy can scale.',
    spike: 'Early game',
    winCon: 'Win lanes, roam with the leads, and close the game on tempo before the scaling comp comes online.',
    play: [ 'Push lanes and roam for kills before 15 minutes', 'Trade every early lead into towers and dragons', 'Force objectives while you out-power them — do not stall' ],
    weakness: 'Scaling comps if you fail to close, and disengage that survives your all-in windows.'
  },
  {
    name: 'Stealth Ambush', emoji: '👻',
    champs: [ {id:'Teemo',role:'Top'}, {id:'Evelynn',role:'Jungle'}, {id:'Akali',role:'Mid'}, {id:'Twitch',role:'Bot'}, {id:'Pyke',role:'Support'} ],
    overview: 'Half the team is invisible. Win the vision game, vanish off the map, and make every dark bush a death sentence.',
    spike: 'Mid game',
    winCon: 'Control vision and ambush isolated targets — they can’t fight what they can’t see.',
    play: [ 'Sweep their wards and deep-ward their jungle', 'Set ambushes on rotation paths and shroom the chokes', 'Convert every pick into a tower or objective' ],
    weakness: 'Control wards, sweepers, and disciplined grouping. A team that never walks alone starves the comp.'
  },
  {
    name: 'Full AP Overload', emoji: '🔮',
    champs: [ {id:'Kennen',role:'Top'}, {id:'Diana',role:'Jungle'}, {id:'Syndra',role:'Mid'}, {id:'Ziggs',role:'Bot'}, {id:'Zyra',role:'Support'} ],
    overview: 'Five magic-damage threats. They can stack all the MR they want — somebody still gets one-shot.',
    spike: 'Mid–late',
    winCon: 'Overload their magic resist — five AP threats means there is always a squishy target to delete.',
    play: [ 'Poke with Syndra, Ziggs and Zyra until they’re half HP', 'Engage with the Kennen + Diana AOE ult combo', 'Rush Void Staff the moment they stack MR' ],
    weakness: 'Heavy MR stacking and magic shields, and having zero physical threat to punish it with.'
  },
  {
    name: 'Juggernaut Rush', emoji: '🚂',
    champs: [ {id:'Darius',role:'Top'}, {id:'Hecarim',role:'Jungle'}, {id:'Gragas',role:'Mid'}, {id:'Nilah',role:'Bot'}, {id:'Alistar',role:'Support'} ],
    overview: 'No poke, no siege, no patience. Five brawlers who sprint at the enemy and win any fight inside melee range.',
    spike: 'Mid game',
    winCon: 'Force messy, extended brawls — you out-sustain and out-damage anyone who stands and fights.',
    play: [ 'Force fights in tight jungle corridors where they can’t kite', 'Flank so the fight starts on top of their carries', 'Keep the pressure on — every won brawl is an objective' ],
    weakness: 'Kiting, disengage, and poke. A good disengage support derails the train before it ever arrives.'
  },
  {
    name: 'Disengage Wall', emoji: '🌪️',
    champs: [ {id:'Gnar',role:'Top'}, {id:'Gragas',role:'Jungle'}, {id:'Anivia',role:'Mid'}, {id:'Ezreal',role:'Bot'}, {id:'Janna',role:'Support'} ],
    overview: 'Every champion says “no”. Knockbacks, walls, and slows that make engaging on this team physically impossible.',
    spike: 'Mid–late',
    winCon: 'Nullify their engage with walls and knockbacks, then win the fight they can no longer leave.',
    play: [ 'Let them engage first — cask, monsoon and wall it away', 'Chip them down as they overextend into nothing', 'Turn and collapse only when their cooldowns are gone' ],
    weakness: 'Poke comps that never engage, and split-pushers who refuse to group — you counter fights that never happen.'
  },
  {
    name: 'Chain CC', emoji: '⛓️',
    champs: [ {id:'Maokai',role:'Top'}, {id:'Zac',role:'Jungle'}, {id:'Lissandra',role:'Mid'}, {id:'Ashe',role:'Bot'}, {id:'Leona',role:'Support'} ],
    overview: 'Someone is always stunned. Layered crowd control means the enemy watches the teamfight instead of playing it.',
    spike: 'Mid–late (once ultimates are up)',
    winCon: 'Chain your CC one spell at a time — their carry stays locked from first engage to death screen.',
    play: [ 'Open with Zac, Maokai or an Ashe arrow on a priority target', 'Layer stuns in sequence, never all at once', 'Kill the locked-down target and roll the fight from there' ],
    weakness: 'Tenacity, cleanses, and QSS. Five Mercury’s Treads turn the comp into a wet noodle.'
  },
];

/* --- Standard build library (shared by Duos + Comps) ------------------------
   Keyed by ddragon champ id = the champion's build in their CONVENTIONAL role.
   (Spicy off-meta picks keep their own inline builds above.) Item names resolve
   to icons via the live item.json; the on-load validator flags any that break. */
const BUILDS = {
  // --- ADCs / carries ---
  Draven:      { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Essence Reaver","Infinity Edge","Bloodthirster","Lord Dominik's Regards"] },
  Ezreal:      { skill: 'Q → E → W', path: ["Doran's Blade","Manamune","Sorcerer's Shoes","Trinity Force","Serylda's Grudge","Death's Dance"] },
  KogMaw:      { skill: 'W → Q → E', path: ["Doran's Blade","Berserker's Greaves","Guinsoo's Rageblade","Nashor's Tooth","Runaan's Hurricane","Wit's End"] },
  Samira:      { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Bloodthirster","Lord Dominik's Regards"] },
  Caitlyn:     { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Rapid Firecannon","Lord Dominik's Regards"] },
  Xayah:       { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Yun Tal Wildarrows","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Vayne:       { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Blade of the Ruined King","Runaan's Hurricane","Wit's End","Lord Dominik's Regards"] },
  Twitch:      { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Guinsoo's Rageblade","Runaan's Hurricane","Nashor's Tooth","Wit's End"] },
  MissFortune: { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Rapid Firecannon","Lord Dominik's Regards"] },
  Ashe:        { skill: 'W → Q → E', path: ["Doran's Blade","Berserker's Greaves","Yun Tal Wildarrows","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Lucian:      { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Essence Reaver","The Collector","Infinity Edge","Lord Dominik's Regards"] },
  Jinx:        { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Nilah:       { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Blade of the Ruined King","Immortal Shieldbow","Phantom Dancer","Death's Dance"] },
  Kalista:     { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Blade of the Ruined King","Runaan's Hurricane","Wit's End","Lord Dominik's Regards"] },
  Sivir:       { skill: 'W → Q → E', path: ["Doran's Blade","Berserker's Greaves","Essence Reaver","Yun Tal Wildarrows","Infinity Edge","Lord Dominik's Regards"] },
  Aphelios:    { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Jhin:        { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Rapid Firecannon","Infinity Edge","Lord Dominik's Regards"] },
  Ziggs:       { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Liandry's Torment","Rabadon's Deathcap","Void Staff","Zhonya's Hourglass"] },

  // --- Supports ---
  Thresh:    { skill: 'Q → E → W', path: ["World Atlas","Mercury's Treads","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Kaenic Rookern"] },
  Karma:     { skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Imperial Mandate","Cosmic Drive","Ardent Censer","Staff of Flowing Water"] },
  Lulu:      { skill: 'E → Q → W', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Echoes of Helia"] },
  Rell:      { skill: 'W → E → Q', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Zeke's Convergence","Knight's Vow","Thornmail"] },
  Morgana:   { skill: 'W → Q → E', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Zhonya's Hourglass","Rabadon's Deathcap"] },
  Rakan:     { skill: 'W → E → Q', path: ["World Atlas","Mercury's Treads","Locket of the Iron Solari","Zeke's Convergence","Knight's Vow","Redemption"] },
  Yuumi:     { skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Echoes of Helia"] },
  Leona:     { skill: 'E → W → Q', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Zeke's Convergence","Knight's Vow","Thornmail"] },
  Zyra:      { skill: 'E → Q → W', path: ["World Atlas","Sorcerer's Shoes","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap","Void Staff"] },
  Nami:      { skill: 'W → E → Q', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Echoes of Helia"] },
  Nautilus:  { skill: 'Q → E → W', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Thornmail"] },
  TahmKench: { skill: 'Q → W → E', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Kaenic Rookern","Jak'Sho, The Protean","Thornmail"] },
  Braum:     { skill: 'Q → E → W', path: ["World Atlas","Mercury's Treads","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Kaenic Rookern"] },

  // --- Mids ---
  Xerath:      { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Void Staff"] },
  Orianna:     { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Archangel's Staff","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] },
  Ahri:        { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
  TwistedFate: { skill: 'W → Q → E', path: ["Doran's Ring","Sorcerer's Shoes","Lich Bane","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },

  // --- Junglers ---
  Nidalee:  { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Lich Bane","Rabadon's Deathcap","Zhonya's Hourglass"] },
  Amumu:    { skill: 'Q → E → W', path: ["Plated Steelcaps","Sunfire Aegis","Liandry's Torment","Riftmaker","Kaenic Rookern","Thornmail"] },
  Ivern:    { skill: 'Q → W → E', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Redemption"] },
  Nocturne: { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","The Collector","Serylda's Grudge","Death's Dance"] },
  Sejuani:  { skill: 'W → E → Q', path: ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Jak'Sho, The Protean","Kaenic Rookern","Thornmail"] },

  // --- Tops ---
  Jayce:    { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Youmuu's Ghostblade","The Collector","Serylda's Grudge","Edge of Night"] },
  Malphite: { skill: 'Q → E → W', path: ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Thornmail","Kaenic Rookern","Jak'Sho, The Protean"] },
  Shen:     { skill: 'Q → W → E', path: ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Spirit Visage","Kaenic Rookern","Thornmail"] },
  Camille:  { skill: 'Q → W → E', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Fiora:    { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Ornn:     { skill: 'Q → W → E', path: ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Thornmail","Kaenic Rookern","Force of Nature"] },
  Kayle:    { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Nashor's Tooth","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] },
  // --- Expanded builds ---
  Aatrox:   { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Eclipse","Sundered Sky","Sterak's Gage","Death's Dance"] },
  Darius:   { skill: 'Q → W → E', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Irelia:   { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Blade of the Ruined King","Sterak's Gage","Death's Dance"] },
  Jax:      { skill: 'Q → W → E', path: ["Doran's Blade","Plated Steelcaps","Blade of the Ruined King","Trinity Force","Sterak's Gage","Death's Dance"] },
  Renekton: { skill: 'Q → W → E', path: ["Doran's Blade","Plated Steelcaps","Black Cleaver","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Riven:    { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Black Cleaver","Sterak's Gage","Death's Dance","Guardian Angel"] },
  LeeSin:   { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Eclipse","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Vi:       { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Black Cleaver","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Viego:    { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Blade of the Ruined King","Death's Dance","Sterak's Gage","Guardian Angel"] },
  Hecarim:  { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Graves:   { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Serylda's Grudge","Lord Dominik's Regards"] },
  Zed:      { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Profane Hydra","Serylda's Grudge","Edge of Night"] },
  Khazix:   { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Profane Hydra","Serylda's Grudge","Edge of Night"] },
  Talon:    { skill: 'Q → W → E', path: ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","Profane Hydra","Serylda's Grudge","Edge of Night"] },
  Katarina: { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
  Fizz:     { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
  Kassadin: { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Rod of Ages","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] },
  Viktor:   { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Void Staff"] },
  Syndra:   { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Luden's Echo","Rabadon's Deathcap","Shadowflame","Void Staff"] },
  Leblanc:  { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Luden's Echo","Rabadon's Deathcap","Shadowflame","Void Staff"] },
  Lux:      { skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Luden's Echo","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
  Yasuo:    { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Immortal Shieldbow","Infinity Edge","Bloodthirster","Death's Dance"] },
  Yone:     { skill: 'Q → E → W', path: ["Doran's Blade","Berserker's Greaves","Immortal Shieldbow","Infinity Edge","Bloodthirster","Death's Dance"] },
  Kaisa:    { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Guinsoo's Rageblade","Nashor's Tooth","Runaan's Hurricane","Rabadon's Deathcap"] },
  Varus:    { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","The Collector","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Zeri:     { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Yun Tal Wildarrows","Infinity Edge","Runaan's Hurricane","Lord Dominik's Regards"] },
  Senna:    { skill: 'Q → W → E', path: ["World Atlas","Berserker's Greaves","The Collector","Infinity Edge","Rapid Firecannon","Lord Dominik's Regards"] },
  Alistar:  { skill: 'W → Q → E', path: ["World Atlas","Plated Steelcaps","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Thornmail"] },
  Blitzcrank:{ skill: 'Q → E → W', path: ["World Atlas","Mercury's Treads","Locket of the Iron Solari","Knight's Vow","Zeke's Convergence","Thornmail"] },
  Milio:    { skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Redemption"] },
  Sona:     { skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Echoes of Helia"] },
  Soraka:   { skill: 'Q → E → W', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Redemption","Staff of Flowing Water","Mikael's Blessing"] },
  Teemo:    { skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Nashor's Tooth","Liandry's Torment","Rylai's Crystal Scepter","Rabadon's Deathcap"] },
  Evelynn:  { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
  Akali:    { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Zhonya's Hourglass","Shadowflame"] },
  Pyke:     { skill: 'Q → E → W', path: ["World Atlas","Mercury's Treads","Youmuu's Ghostblade","Umbral Glaive","Edge of Night","Serylda's Grudge"] },
  Kennen:   { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Rabadon's Deathcap","Zhonya's Hourglass","Void Staff"] },
  Diana:    { skill: 'Q → W → E', path: ["Doran's Ring","Sorcerer's Shoes","Nashor's Tooth","Riftmaker","Rabadon's Deathcap","Zhonya's Hourglass"] },
  Gragas:   { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Hextech Rocketbelt","Cosmic Drive","Rabadon's Deathcap","Zhonya's Hourglass"] },
  Gnar:     { skill: 'Q → W → E', path: ["Doran's Blade","Berserker's Greaves","Trinity Force","Black Cleaver","Sterak's Gage","Guardian Angel"] },
  Anivia:   { skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Rod of Ages","Archangel's Staff","Rabadon's Deathcap","Zhonya's Hourglass"] },
  Janna:    { skill: 'W → Q → E', path: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Redemption"] },
  Maokai:   { skill: 'Q → E → W', path: ["Plated Steelcaps","Sunfire Aegis","Liandry's Torment","Thornmail","Kaenic Rookern","Force of Nature"] },
  Zac:      { skill: 'W → Q → E', path: ["Plated Steelcaps","Sunfire Aegis","Spirit Visage","Thornmail","Kaenic Rookern","Jak'Sho, The Protean"] },
  Lissandra:{ skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Zhonya's Hourglass","Rabadon's Deathcap","Void Staff"] },
  // --- Added for the classic solo roster ---
  Garen:    { skill: 'Q → E → W', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Sett:     { skill: 'W → E → Q', path: ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"] },
  KSante:   { skill: 'Q → W → E', path: ["Plated Steelcaps","Iceborn Gauntlet","Sunfire Aegis","Jak'Sho, The Protean","Kaenic Rookern","Thornmail"] },
  Gwen:     { skill: 'Q → E → W', path: ["Doran's Ring","Sorcerer's Shoes","Nashor's Tooth","Riftmaker","Rabadon's Deathcap","Zhonya's Hourglass"] },
  Kayn:     { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Eclipse","Sundered Sky","Sterak's Gage","Death's Dance"] },
  JarvanIV: { skill: 'Q → E → W', path: ["Doran's Blade","Mercury's Treads","Black Cleaver","Sterak's Gage","Death's Dance","Guardian Angel"] },
  Elise:    { skill: 'E → Q → W', path: ["Doran's Ring","Sorcerer's Shoes","Malignance","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass"] },
};

/* --- Standard rune library (shared by Duos + Comps) --------------------------
   Keyed by ddragon champ id = 'Keystone · Secondary tree' in the champion's
   CONVENTIONAL role. Off-meta picks (SPICY / SPICY_DUOS) carry inline `rune`
   overrides in their build objects. Keystone identities are near-evergreen.
   Names resolve to icons via the live runesReforged.json; validator flags drift. */
const RUNES = {
  // ADCs / carries
  Draven: 'Hail of Blades · Precision', Ezreal: 'Press the Attack · Sorcery',
  KogMaw: 'Lethal Tempo · Sorcery', Samira: 'Conqueror · Domination',
  Caitlyn: 'Fleet Footwork · Inspiration', Xayah: 'Lethal Tempo · Domination',
  Vayne: 'Lethal Tempo · Domination', Twitch: 'Lethal Tempo · Domination',
  MissFortune: 'Press the Attack · Sorcery', Ashe: 'Lethal Tempo · Inspiration',
  Lucian: 'Press the Attack · Inspiration', Jinx: 'Lethal Tempo · Sorcery',
  Nilah: 'Conqueror · Inspiration', Kalista: 'Hail of Blades · Precision',
  Sivir: 'Fleet Footwork · Sorcery', Aphelios: 'Fleet Footwork · Sorcery',
  Jhin: 'Fleet Footwork · Sorcery', Ziggs: 'Arcane Comet · Inspiration',
  Kaisa: 'Hail of Blades · Precision', Varus: 'Lethal Tempo · Sorcery',
  Zeri: 'Lethal Tempo · Sorcery', Senna: 'Fleet Footwork · Sorcery',
  // Supports
  Thresh: 'Aftershock · Inspiration', Karma: 'Summon Aery · Inspiration',
  Lulu: 'Summon Aery · Inspiration', Rell: 'Aftershock · Domination',
  Morgana: 'Arcane Comet · Inspiration', Rakan: 'Guardian · Inspiration',
  Yuumi: 'Summon Aery · Inspiration', Leona: 'Aftershock · Domination',
  Zyra: 'Arcane Comet · Domination', Nami: 'Summon Aery · Inspiration',
  Nautilus: 'Aftershock · Inspiration', TahmKench: 'Grasp of the Undying · Inspiration',
  Braum: 'Guardian · Inspiration', Alistar: 'Aftershock · Inspiration',
  Blitzcrank: 'Aftershock · Inspiration', Milio: 'Summon Aery · Inspiration',
  Sona: 'Summon Aery · Inspiration', Soraka: 'Summon Aery · Inspiration',
  Janna: 'Summon Aery · Inspiration', Pyke: 'Hail of Blades · Inspiration',
  // Mids
  Xerath: 'Arcane Comet · Inspiration', Orianna: 'Arcane Comet · Inspiration',
  Ahri: 'Electrocute · Sorcery', TwistedFate: 'Stormraider’s Surge · Inspiration',
  Katarina: 'Conqueror · Domination', Fizz: 'Electrocute · Sorcery',
  Kassadin: 'Fleet Footwork · Sorcery', Viktor: 'Arcane Comet · Inspiration',
  Syndra: 'Arcane Comet · Inspiration', Leblanc: 'Electrocute · Sorcery',
  Lux: 'Arcane Comet · Inspiration', Yasuo: 'Lethal Tempo · Resolve',
  Yone: 'Lethal Tempo · Resolve', Zed: 'Electrocute · Precision',
  Talon: 'Electrocute · Sorcery', Akali: 'Conqueror · Resolve',
  Anivia: 'Arcane Comet · Inspiration', Lissandra: 'Arcane Comet · Inspiration',
  Kennen: 'Electrocute · Sorcery', Gragas: 'Stormraider’s Surge · Resolve',
  // Junglers
  Nidalee: 'Dark Harvest · Sorcery', Amumu: 'Aftershock · Inspiration',
  Ivern: 'Guardian · Inspiration', Nocturne: 'Lethal Tempo · Domination',
  Sejuani: 'Aftershock · Inspiration', LeeSin: 'Conqueror · Domination',
  Elise: 'Electrocute · Sorcery', Graves: 'Fleet Footwork · Sorcery',
  Hecarim: 'Conqueror · Sorcery', Vi: 'Conqueror · Inspiration',
  Viego: 'Conqueror · Domination', Khazix: 'Dark Harvest · Precision',
  Evelynn: 'Electrocute · Sorcery', Diana: 'Conqueror · Domination',
  Zac: 'Aftershock · Inspiration', Maokai: 'Grasp of the Undying · Inspiration',
  // Tops
  Jayce: 'First Strike · Sorcery', Malphite: 'Grasp of the Undying · Sorcery',
  Shen: 'Grasp of the Undying · Inspiration', Camille: 'Grasp of the Undying · Sorcery',
  Fiora: 'Conqueror · Sorcery', Ornn: 'Grasp of the Undying · Inspiration',
  Kayle: 'Lethal Tempo · Sorcery', Aatrox: 'Conqueror · Sorcery',
  Darius: 'Conqueror · Sorcery', Irelia: 'Conqueror · Resolve',
  Jax: 'Conqueror · Resolve', Renekton: 'Conqueror · Resolve',
  Riven: 'Conqueror · Sorcery', Gnar: 'Grasp of the Undying · Sorcery',
  Teemo: 'Press the Attack · Sorcery',
  // Added for the classic solo roster
  Garen: 'Conqueror · Resolve', Sett: 'Conqueror · Resolve', KSante: 'Grasp of the Undying · Resolve',
  Gwen: 'Conqueror · Sorcery', Kayn: 'Conqueror · Domination', JarvanIV: 'Conqueror · Resolve',
};

/* --- Fallback build templates -----------------------------------------------
   Used by the Team Analyzer when a picked champion has no curated BUILDS entry
   (it allows all 173 champs). Chosen by damage type + ddragon class so every
   pick still shows a sensible build. All items must exist in ITEM_USES. */
const BUILD_TEMPLATES = {
  ap:        ["Doran's Ring","Sorcerer's Shoes","Rabadon's Deathcap","Shadowflame","Zhonya's Hourglass","Void Staff"],
  marksman:  ["Doran's Blade","Berserker's Greaves","Infinity Edge","The Collector","Runaan's Hurricane","Lord Dominik's Regards"],
  assassin:  ["Doran's Blade","Mercury's Treads","Youmuu's Ghostblade","The Collector","Serylda's Grudge","Edge of Night"],
  bruiser:   ["Doran's Blade","Plated Steelcaps","Trinity Force","Sterak's Gage","Death's Dance","Guardian Angel"],
  tank:      ["Plated Steelcaps","Sunfire Aegis","Iceborn Gauntlet","Thornmail","Kaenic Rookern","Jak'Sho, The Protean"],
  enchanter: ["World Atlas","Sorcerer's Shoes","Moonstone Renewer","Ardent Censer","Staff of Flowing Water","Redemption"],
};

/* --- Item "main use" captions ----------------------------------------------
   Riot leaves item.json's plaintext empty for most legendaries, so these are
   hand-written. Item PURPOSE is evergreen (Void Staff = pen, Zhonya's = stasis),
   so this rarely needs touching. The validator warns if a built item lacks one. */
const ITEM_USES = {
  "Archangel's Staff": 'Big AP + mana pool',
  "Ardent Censer": 'Buffs allied attacks',
  "Berserker's Greaves": 'Attack-speed boots',
  "Blade of the Ruined King": 'Shreds tanks, sustains',
  "Bloodthirster": 'Lifesteal + overheal shield',
  "Black Cleaver": 'Armor shred + health',
  "Eclipse": 'Shield + burst combo',
  "Sundered Sky": 'Heal on first hit',
  "Profane Hydra": 'AoE cleave + execute',
  "Hextech Rocketbelt": 'Dash + burst',
  "Luden's Echo": 'Burst mana + haste',
  "Mikael's Blessing": 'Cleanses CC + heals',
  "Cosmic Drive": 'Ability haste + move speed',
  "Cryptbloom": 'Magic pen + heal cut',
  "Death's Dance": 'Delays burst, bruiser survival',
  "Doran's Blade": 'AD lane starter',
  "Doran's Ring": 'AP lane starter',
  "Doran's Shield": 'Durable lane starter',
  "Echoes of Helia": 'Heals + procs damage',
  "Edge of Night": 'Spell shield + lethality',
  "Essence Reaver": 'Refunds mana on crit',
  "Force of Nature": 'Anti-magic + move speed',
  "Guardian Angel": 'Revives you once',
  "Guinsoo's Rageblade": 'On-hit DPS scaling',
  "Iceborn Gauntlet": 'AoE slow + armor',
  "Immortal Shieldbow": 'Lifesteal + panic shield',
  "Imperial Mandate": 'Bonus damage on CC',
  "Infinity Edge": 'Huge crit damage',
  "Jak'Sho, The Protean": 'Scaling all-round tank',
  "Kaenic Rookern": 'Massive magic shield',
  "Knight's Vow": 'Guards a chosen ally',
  "Liandry's Torment": 'Burns high-HP targets',
  "Lich Bane": 'Empowered auto burst',
  "Locket of the Iron Solari": 'Team-wide shield active',
  "Lord Dominik's Regards": 'Armor pen vs tanks',
  "Malignance": 'Ult haste + burn zone',
  "Manamune": 'Mana into attack damage',
  "Mercury's Treads": 'MR boots + tenacity',
  "Moonstone Renewer": 'Chain-heals allies',
  "Nashor's Tooth": 'AP + attack speed',
  "Phantom Dancer": 'Attack speed + ghosting',
  "Plated Steelcaps": 'Armor boots vs autos',
  "Rabadon's Deathcap": 'Amplifies total AP',
  "Rapid Firecannon": 'Extra range + proc',
  "Redemption": 'Global area heal',
  "Riftmaker": 'Sustained AP + true damage',
  "Rod of Ages": 'Scales HP, mana, AP',
  "Runaan's Hurricane": 'Hits extra targets',
  "Rylai's Crystal Scepter": 'Slows on ability hit',
  "Serylda's Grudge": 'Armor pen + slow',
  "Shadowflame": 'Burst pen vs squishies',
  "Sorcerer's Shoes": 'Magic-pen boots',
  "Spirit Visage": 'Boosts healing + MR',
  "Staff of Flowing Water": 'AP + haste to allies',
  "Sterak's Gage": 'Anti-burst shield',
  "Sunfire Aegis": 'Tanky AoE burn',
  "The Collector": 'Executes low enemies',
  "Thornmail": 'Reflects + cuts healing',
  "Trinity Force": 'All-round bruiser stats',
  "Umbral Glaive": 'Destroys enemy wards',
  "Void Staff": 'Magic penetration',
  "Wit's End": 'On-hit magic + MR',
  "World Atlas": 'Support gold + wards',
  "Youmuu's Ghostblade": 'Lethality + roam speed',
  "Yun Tal Wildarrows": 'Crit + AD scaling',
  "Zeke's Convergence": 'Empowers your carry',
  "Zhonya's Hourglass": 'Stasis to dodge burst',
};

/* --- Team Analyzer: champion traits + archetype rules -----------------------
   dmg: 'AD' | 'AP' | 'hybrid' | 'tank' | 'utility'
   traits vocab: engage poke dive peel cc scaling early splitpush waveclear
                 mobility aoe sustain frontline pick utility hypercarry burst
   Champions not listed fall back to their ddragon class (CLASS_FALLBACK). */
const CHAMP_TRAITS = {
  // Frontline / tanks / engage supports
  Malphite:  { dmg:'AP',   traits:['engage','aoe','frontline','cc'] },
  Leona:     { dmg:'tank', traits:['engage','cc','frontline','pick'] },
  Nautilus:  { dmg:'tank', traits:['engage','cc','frontline','pick'] },
  Rell:      { dmg:'AP',   traits:['engage','aoe','cc','frontline'] },
  Amumu:     { dmg:'AP',   traits:['engage','aoe','cc','frontline'] },
  Sejuani:   { dmg:'tank', traits:['engage','aoe','cc','frontline'] },
  Ornn:      { dmg:'tank', traits:['engage','aoe','cc','frontline','scaling'] },
  Braum:     { dmg:'tank', traits:['peel','cc','frontline'] },
  TahmKench: { dmg:'tank', traits:['peel','frontline','pick'] },
  Shen:      { dmg:'tank', traits:['frontline','splitpush','peel'] },
  Thresh:    { dmg:'utility', traits:['pick','cc','peel','engage'] },
  // Bruisers / tops
  Camille:   { dmg:'AD',   traits:['dive','splitpush','pick','mobility'] },
  Fiora:     { dmg:'AD',   traits:['splitpush','scaling','dive'] },
  Jayce:     { dmg:'AD',   traits:['poke','early'] },
  Sett:      { dmg:'AD',   traits:['engage','frontline','cc'] },
  Singed:    { dmg:'AP',   traits:['splitpush','frontline'] },
  Vladimir:  { dmg:'AP',   traits:['scaling','aoe','poke'] },
  Mordekaiser:{ dmg:'AP',  traits:['dive','frontline','pick'] },
  Kayle:     { dmg:'hybrid',traits:['scaling','hypercarry','waveclear'] },
  // Assassins / divers / pick mids
  Nocturne:  { dmg:'AD',   traits:['dive','pick','engage','mobility'] },
  Pyke:      { dmg:'AD',   traits:['pick','mobility','burst'] },
  Ahri:      { dmg:'AP',   traits:['pick','burst','mobility','poke'] },
  // Mages
  Xerath:    { dmg:'AP',   traits:['poke','waveclear'] },
  Ziggs:     { dmg:'AP',   traits:['poke','waveclear','splitpush'] },
  Orianna:   { dmg:'AP',   traits:['aoe','poke','peel'] },
  Veigar:    { dmg:'AP',   traits:['burst','scaling','cc'] },
  Cassiopeia:{ dmg:'AP',   traits:['scaling','waveclear','sustain'] },
  Heimerdinger:{ dmg:'AP', traits:['poke','waveclear','splitpush'] },
  Neeko:     { dmg:'AP',   traits:['engage','aoe','burst','pick'] },
  Swain:     { dmg:'AP',   traits:['sustain','aoe','cc','frontline'] },
  Zilean:    { dmg:'AP',   traits:['peel','cc','utility'] },
  Karthus:   { dmg:'AP',   traits:['scaling','waveclear','aoe'] },
  Seraphine: { dmg:'AP',   traits:['aoe','peel','poke','utility'] },
  TwistedFate:{ dmg:'AP',  traits:['pick','poke'] },
  // Junglers
  Nidalee:   { dmg:'AP',   traits:['poke','early','mobility'] },
  Ivern:     { dmg:'AP',   traits:['peel','utility','engage'] },
  // ADCs
  Draven:    { dmg:'AD',   traits:['early'] },
  Ezreal:    { dmg:'AD',   traits:['poke','scaling','mobility'] },
  KogMaw:    { dmg:'AD',   traits:['scaling','hypercarry','waveclear'] },
  Samira:    { dmg:'AD',   traits:['dive','aoe','scaling'] },
  Caitlyn:   { dmg:'AD',   traits:['poke','early','waveclear'] },
  Xayah:     { dmg:'AD',   traits:['scaling','peel','aoe'] },
  Vayne:     { dmg:'AD',   traits:['scaling','hypercarry','dive'] },
  Twitch:    { dmg:'AD',   traits:['scaling','hypercarry','aoe'] },
  MissFortune:{ dmg:'AD',  traits:['aoe','poke','early'] },
  Ashe:      { dmg:'AD',   traits:['poke','cc','pick','utility'] },
  Lucian:    { dmg:'AD',   traits:['early','mobility','dive'] },
  Jinx:      { dmg:'AD',   traits:['scaling','hypercarry','aoe','waveclear'] },
  Nilah:     { dmg:'AD',   traits:['scaling','aoe','dive'] },
  Kalista:   { dmg:'AD',   traits:['early','mobility','peel'] },
  Sivir:     { dmg:'AD',   traits:['waveclear','poke','engage'] },
  Aphelios:  { dmg:'AD',   traits:['scaling','hypercarry'] },
  Jhin:      { dmg:'AD',   traits:['poke','pick','early'] },
  Tristana:  { dmg:'AD',   traits:['dive','scaling','splitpush'] },
  // Supports / enchanters
  Karma:     { dmg:'AP',   traits:['poke','peel','utility','engage'] },
  Lulu:      { dmg:'AP',   traits:['peel','utility','scaling'] },
  Morgana:   { dmg:'AP',   traits:['pick','cc','peel'] },
  Rakan:     { dmg:'AP',   traits:['engage','peel','mobility','cc'] },
  Yuumi:     { dmg:'AP',   traits:['peel','utility','scaling'] },
  Zyra:      { dmg:'AP',   traits:['poke','aoe','cc'] },
  Nami:      { dmg:'AP',   traits:['peel','utility','poke','cc'] },
  Teemo:     { dmg:'AP',   traits:['splitpush','poke'] },

  // === Expanded roster (these entries also carry `roles`) ===
  // Top / bruisers / tanks
  Aatrox:    { dmg:'AD',   roles:['Top'], traits:['dive','frontline','sustain'] },
  Darius:    { dmg:'AD',   roles:['Top'], traits:['frontline','early','sustain'] },
  Garen:     { dmg:'AD',   roles:['Top'], traits:['frontline','early'] },
  Gnar:      { dmg:'AD',   roles:['Top'], traits:['engage','poke','frontline'] },
  Gwen:      { dmg:'AP',   roles:['Top'], traits:['dive','scaling','splitpush'] },
  Illaoi:    { dmg:'AD',   roles:['Top'], traits:['frontline','early','sustain'] },
  Irelia:    { dmg:'AD',   roles:['Top','Mid'], traits:['dive','splitpush','scaling'] },
  Jax:       { dmg:'AD',   roles:['Top','Jungle'], traits:['splitpush','scaling','dive'] },
  Kled:      { dmg:'AD',   roles:['Top'], traits:['engage','early','frontline'] },
  KSante:    { dmg:'tank', roles:['Top'], traits:['frontline','engage','cc'] },
  Maokai:    { dmg:'tank', roles:['Top','Support','Jungle'], traits:['engage','cc','frontline','sustain'] },
  Nasus:     { dmg:'AD',   roles:['Top'], traits:['scaling','frontline','splitpush'] },
  Renekton:  { dmg:'AD',   roles:['Top'], traits:['dive','early','frontline'] },
  Riven:     { dmg:'AD',   roles:['Top'], traits:['dive','splitpush','early','mobility'] },
  Sion:      { dmg:'tank', roles:['Top'], traits:['engage','frontline','cc','scaling'] },
  Urgot:     { dmg:'AD',   roles:['Top'], traits:['frontline','early','sustain'] },
  Volibear:  { dmg:'AD',   roles:['Top','Jungle'], traits:['engage','dive','frontline'] },
  Yorick:    { dmg:'AD',   roles:['Top'], traits:['splitpush','frontline','scaling'] },
  Tryndamere:{ dmg:'AD',   roles:['Top'], traits:['splitpush','scaling','early'] },
  Chogath:   { dmg:'AP',   roles:['Top','Mid'], traits:['frontline','cc','scaling','sustain'] },
  DrMundo:   { dmg:'tank', roles:['Top'], traits:['frontline','sustain','scaling'] },
  Gangplank: { dmg:'AD',   roles:['Top'], traits:['poke','scaling','splitpush'] },
  Kennen:    { dmg:'AP',   roles:['Top','Mid'], traits:['engage','aoe','poke'] },
  Poppy:     { dmg:'tank', roles:['Top','Jungle','Support'], traits:['engage','frontline','cc','peel'] },
  MonkeyKing:{ dmg:'AD',   roles:['Top','Jungle'], traits:['engage','dive','frontline'] },
  // Junglers
  LeeSin:    { dmg:'AD',   roles:['Jungle'], traits:['early','pick','engage','mobility'] },
  Elise:     { dmg:'AP',   roles:['Jungle'], traits:['dive','pick','early'] },
  Graves:    { dmg:'AD',   roles:['Jungle'], traits:['early','scaling','burst'] },
  Hecarim:   { dmg:'AD',   roles:['Jungle'], traits:['engage','dive','mobility','frontline'] },
  JarvanIV:  { dmg:'AD',   roles:['Jungle'], traits:['engage','dive','cc','frontline'] },
  Kayn:      { dmg:'AD',   roles:['Jungle'], traits:['dive','scaling','burst','mobility'] },
  Khazix:    { dmg:'AD',   roles:['Jungle'], traits:['dive','burst','pick','mobility'] },
  Kindred:   { dmg:'AD',   roles:['Jungle'], traits:['scaling','early','pick'] },
  MasterYi:  { dmg:'AD',   roles:['Jungle'], traits:['scaling','hypercarry','splitpush'] },
  Rengar:    { dmg:'AD',   roles:['Jungle'], traits:['dive','burst','pick','mobility'] },
  Vi:        { dmg:'AD',   roles:['Jungle'], traits:['engage','dive','cc','pick'] },
  Viego:     { dmg:'AD',   roles:['Jungle'], traits:['dive','scaling','mobility'] },
  Warwick:   { dmg:'hybrid',roles:['Jungle'], traits:['dive','sustain','engage'] },
  XinZhao:   { dmg:'AD',   roles:['Jungle'], traits:['engage','dive','early'] },
  Zac:       { dmg:'AP',   roles:['Jungle'], traits:['engage','aoe','cc','frontline'] },
  Ekko:      { dmg:'AP',   roles:['Jungle','Mid'], traits:['dive','burst','pick','mobility'] },
  Diana:     { dmg:'AP',   roles:['Jungle','Mid'], traits:['dive','aoe','burst'] },
  Fiddlesticks:{ dmg:'AP', roles:['Jungle'], traits:['engage','aoe','cc'] },
  Rammus:    { dmg:'tank', roles:['Jungle'], traits:['engage','frontline','cc'] },
  Nunu:      { dmg:'AP',   roles:['Jungle'], traits:['engage','cc','peel'] },
  Gragas:    { dmg:'AP',   roles:['Jungle','Top','Mid'], traits:['engage','cc','peel','frontline'] },
  Briar:     { dmg:'AD',   roles:['Jungle'], traits:['dive','sustain','engage'] },
  Belveth:   { dmg:'AD',   roles:['Jungle'], traits:['scaling','dive','mobility'] },
  Shyvana:   { dmg:'hybrid',roles:['Jungle'], traits:['scaling','dive','frontline'] },
  Skarner:   { dmg:'tank', roles:['Jungle'], traits:['engage','cc','frontline','pick'] },
  Evelynn:   { dmg:'AP',   roles:['Jungle'], traits:['dive','burst','pick','mobility'] },
  Taliyah:   { dmg:'AP',   roles:['Jungle','Mid'], traits:['poke','waveclear','pick'] },
  // Mids
  Akali:     { dmg:'AP',   roles:['Mid','Top'], traits:['dive','burst','pick','mobility'] },
  Anivia:    { dmg:'AP',   roles:['Mid'], traits:['waveclear','cc','scaling','poke'] },
  Annie:     { dmg:'AP',   roles:['Mid','Support'], traits:['burst','cc','engage'] },
  AurelionSol:{ dmg:'AP',  roles:['Mid'], traits:['scaling','waveclear','poke'] },
  Azir:      { dmg:'AP',   roles:['Mid'], traits:['scaling','poke','waveclear','aoe'] },
  Fizz:      { dmg:'AP',   roles:['Mid'], traits:['dive','burst','pick','mobility'] },
  Galio:     { dmg:'AP',   roles:['Mid','Support'], traits:['engage','aoe','cc','frontline'] },
  Kassadin:  { dmg:'AP',   roles:['Mid'], traits:['scaling','burst','mobility'] },
  Katarina:  { dmg:'AP',   roles:['Mid'], traits:['dive','burst','aoe','mobility'] },
  Leblanc:   { dmg:'AP',   roles:['Mid'], traits:['pick','burst','mobility'] },
  Lissandra: { dmg:'AP',   roles:['Mid'], traits:['engage','cc','burst','aoe'] },
  Lux:       { dmg:'AP',   roles:['Mid','Support'], traits:['poke','burst','cc'] },
  Malzahar:  { dmg:'AP',   roles:['Mid'], traits:['waveclear','pick','cc'] },
  Pantheon:  { dmg:'AD',   roles:['Mid','Top','Support'], traits:['early','engage','pick'] },
  Qiyana:    { dmg:'AD',   roles:['Mid'], traits:['dive','burst','aoe','mobility'] },
  Ryze:      { dmg:'AP',   roles:['Mid'], traits:['scaling','waveclear'] },
  Sylas:     { dmg:'AP',   roles:['Mid'], traits:['dive','sustain','aoe'] },
  Syndra:    { dmg:'AP',   roles:['Mid'], traits:['poke','burst','scaling'] },
  Talon:     { dmg:'AD',   roles:['Mid'], traits:['pick','burst','mobility'] },
  Velkoz:    { dmg:'AP',   roles:['Mid','Support'], traits:['poke','burst','waveclear'] },
  Vex:       { dmg:'AP',   roles:['Mid'], traits:['poke','burst','cc'] },
  Viktor:    { dmg:'AP',   roles:['Mid'], traits:['scaling','waveclear','aoe'] },
  Yasuo:     { dmg:'AD',   roles:['Mid','Top'], traits:['scaling','dive','mobility'] },
  Yone:      { dmg:'AD',   roles:['Mid','Top'], traits:['dive','scaling','mobility'] },
  Zed:       { dmg:'AD',   roles:['Mid'], traits:['dive','burst','pick','mobility'] },
  Zoe:       { dmg:'AP',   roles:['Mid'], traits:['poke','burst','pick'] },
  Corki:     { dmg:'hybrid',roles:['Mid'], traits:['poke','scaling','waveclear'] },
  Naafiri:   { dmg:'AD',   roles:['Mid'], traits:['dive','burst','mobility'] },
  // Bot
  Kaisa:     { dmg:'hybrid',roles:['Bot'], traits:['scaling','dive','hypercarry'] },
  Varus:     { dmg:'AD',   roles:['Bot','Mid'], traits:['poke','scaling','cc'] },
  Zeri:      { dmg:'AD',   roles:['Bot'], traits:['scaling','hypercarry','mobility'] },
  Senna:     { dmg:'AD',   roles:['Bot','Support'], traits:['poke','scaling','utility','peel'] },
  Smolder:   { dmg:'AD',   roles:['Bot'], traits:['scaling','hypercarry','waveclear'] },
  // Supports
  Alistar:   { dmg:'tank', roles:['Support'], traits:['engage','cc','peel','frontline'] },
  Bard:      { dmg:'AP',   roles:['Support'], traits:['pick','utility','peel'] },
  Blitzcrank:{ dmg:'AP',   roles:['Support'], traits:['pick','cc','engage'] },
  Brand:     { dmg:'AP',   roles:['Support','Mid'], traits:['poke','burst','aoe'] },
  Janna:     { dmg:'AP',   roles:['Support'], traits:['peel','utility','poke'] },
  Milio:     { dmg:'AP',   roles:['Support'], traits:['peel','utility','scaling'] },
  Renata:    { dmg:'AP',   roles:['Support'], traits:['peel','cc','utility','engage'] },
  Sona:      { dmg:'AP',   roles:['Support'], traits:['peel','utility','poke','scaling'] },
  Soraka:    { dmg:'utility',roles:['Support'], traits:['peel','utility','sustain'] },
  Taric:     { dmg:'utility',roles:['Support'], traits:['peel','engage','cc','sustain'] },
};

// Roles for the original curated champions (the expanded entries carry their own).
const CHAMP_ROLES = {
  Malphite:['Top','Support'], Leona:['Support'], Nautilus:['Support'], Rell:['Support'],
  Amumu:['Jungle','Support'], Sejuani:['Jungle'], Ornn:['Top'], Braum:['Support'],
  TahmKench:['Support','Top'], Shen:['Top','Support'], Camille:['Top'], Fiora:['Top'],
  Jayce:['Top','Mid'], Sett:['Top','Support'], Singed:['Top'], Vladimir:['Mid','Top'],
  Mordekaiser:['Top','Mid'], Kayle:['Top'], Nocturne:['Jungle'], Pyke:['Support','Mid'],
  Ahri:['Mid'], Xerath:['Mid','Support'], Ziggs:['Mid','Bot'], Orianna:['Mid'],
  Veigar:['Mid','Support'], Cassiopeia:['Mid'], Heimerdinger:['Mid','Support'],
  Neeko:['Mid','Support'], Swain:['Support','Mid'], Zilean:['Support','Mid'],
  Karthus:['Jungle','Mid'], Seraphine:['Support','Bot','Mid'], TwistedFate:['Mid'],
  Nidalee:['Jungle'], Ivern:['Jungle'], Draven:['Bot'], Ezreal:['Bot'], KogMaw:['Bot'],
  Samira:['Bot'], Caitlyn:['Bot'], Xayah:['Bot'], Vayne:['Bot','Top'], Twitch:['Bot'],
  MissFortune:['Bot'], Ashe:['Bot'], Lucian:['Bot'], Jinx:['Bot'], Nilah:['Bot'],
  Kalista:['Bot'], Sivir:['Bot'], Aphelios:['Bot'], Jhin:['Bot'], Tristana:['Bot'],
  Karma:['Support'], Lulu:['Support'], Morgana:['Support','Mid'], Rakan:['Support'],
  Yuumi:['Support'], Zyra:['Support'], Nami:['Support'], Teemo:['Top','Support'],
};

// Roles inferred from ddragon class, for champions not in either map above.
const CLASS_ROLES = {
  Marksman: ['Bot'], Mage: ['Mid'], Assassin: ['Mid'],
  Tank: ['Top', 'Support'], Fighter: ['Top', 'Jungle'], Support: ['Support'],
};

// Fallback traits by ddragon class tag, for champions not curated above.
const CLASS_FALLBACK = {
  Marksman: { dmg:'AD',      traits:['scaling'] },
  Mage:     { dmg:'AP',      traits:['poke'] },
  Assassin: { dmg:'hybrid',  traits:['dive','burst','mobility'] },
  Tank:     { dmg:'tank',    traits:['engage','frontline','cc'] },
  Fighter:  { dmg:'AD',      traits:['frontline','dive'] },
  Support:  { dmg:'utility', traits:['peel','utility'] },
};

// Archetypes scored from the team's aggregated traits. Highest score wins.
const ARCHETYPES = [
  { key:'Teamfight Wombo', emoji:'💥', sig:{ engage:2, aoe:2, cc:1, frontline:1 },
    winCon:'Group as five and force teamfights on objectives — your AOE engage wins any clustered fight.',
    play:['Look for a flank or flash-engage to start the fight','Layer your CC and AOE onto their grouped team','Fight on top of objectives so a won fight = a free Baron or Dragon'] },
  { key:'Poke & Siege', emoji:'🎯', sig:{ poke:3, waveclear:1 },
    winCon:'Chip them down from range and take towers before they can ever force a fight.',
    play:['Poke them off the objective, then siege the tower','Keep your spacing — never facecheck or get caught','Snowball the health lead into objectives'] },
  { key:'Scale & Outlast', emoji:'⏳', sig:{ scaling:3, hypercarry:2, peel:1 },
    winCon:'Reach your item spikes and out-scale them — late-game fights are yours by default.',
    play:['Farm safely and trade objectives for time','Dodge coin-flip early skirmishes','Once online, group and fight — you simply win late'] },
  { key:'Dive the Backline', emoji:'🗡️', sig:{ dive:3, mobility:1, burst:1 },
    winCon:'Collapse on their carries from multiple angles and delete them before a real 5v5 begins.',
    play:['Find flank and pick angles onto their backline','Commit together — half-dives just feed','Kill the carry first, then clean up the 5v4'] },
  { key:'Early Snowball', emoji:'⚡', sig:{ early:3 },
    winCon:'Win lanes, snowball the leads across the map, and close before they scale.',
    play:['Play aggressive and roam for early kills','Convert every lead into towers and dragons','Force the pace — do not let the game go late'] },
  { key:'Split Push', emoji:'🗺️', sig:{ splitpush:3, mobility:1 },
    winCon:'Apply side-lane pressure they cannot answer, and trade objectives across the map.',
    play:['Send your duelist to a side lane','Trade — take objectives while they respond','Use the map pressure to force bad answers'] },
  { key:'Protect the Carry', emoji:'🛡️', sig:{ peel:2, hypercarry:2, utility:1 },
    winCon:'Keep your hypercarry alive through the fight and let them melt the enemy front-to-back.',
    play:['Play around your carry’s safety at all times','Peel and body-block divers off them','Let the enemy commit, then win the extended fight'] },
  { key:'Pick & Catch', emoji:'🎣', sig:{ pick:3, cc:1 },
    winCon:'Catch someone out of position with your CC, then turn the numbers into objectives.',
    play:['Control vision and lurk at choke points','Land your pick, then collapse for the 5v4','Snowball the advantage into towers and objectives'] },
];

const ROLE_ORDER = { Top: 0, Jungle: 1, Mid: 2, Bot: 3, Support: 4 };
